### ISSUE TITLE
PHP errors

### ISSUE THREAD

**Issue by jfkeegan** [plesk/wpchk#24]
I run this on a Plesk server with a number of WordPress sites, and the majority of sites show the following error:

`PHP Notice:  Constant ABSPATH already defined in phar:///usr/local/bin/wpchk/vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php(1153) : eval()'d code on line 34`

On another server, simply running wpchk results in this error:

```
[root@server ~]# wpchk
PHP Parse error:  syntax error, unexpected '[' in phar:///usr/local/bin/wpchk/src/Command/Scan.php on line 1
[root@server ~]# wpchk --update
PHP Parse error:  syntax error, unexpected '[' in phar:///usr/local/bin/wpchk/src/HttpClient.php on line 1
```

Any suggestions?

**Comment by laurisb** [comment]
Please, provide some information about your environment, at least PHP and WordPress versions. Without this information is hard to guess what's wrong.

First issue could be caused by ancient WordPress versions (< 3.7) or by manually modified wp-config.php. Please, see [this link](https://github.com/wp-cli/wp-cli/issues/1315#issuecomment-51492225) for more infomation.

The minimum PHP version requirement for WPchk is PHP 5.4 and this is why you are getting parse errors.
